### ISSUE TITLE
Integrate Chatwoot inside Nextjs project

### ISSUE THREAD

**Issue by siddharth2798** [aviyelverse/Open-Source-Requests#118]
### **Integrate Chatwoot inside Nextjs project**

   - **Posted by**: Aviyel Team
   - [Check Status](https://sturdy-locust-74a.notion.site/Chatwoot-27475c4c2ebd48c2a456e6caf525434f)
   - **Standard**: _Unpaid_

**Comment by Dhravya** [comment]
Hi, I can do this!

**Comment by siddharth2798** [comment]
https://github.com/aviyelverse/project-templates-and-demos/pull/2
review pending

**Comment by Dhravya** [comment]
Hey there, please let me know if you want anything to be fixed. Waiting to be merged

**Comment by siddharth2798** [comment]
Merged!
