### ISSUE TITLE
Integrate Chatwoot inside Vuejs project

### ISSUE THREAD

**Issue by siddharth2798** [aviyelverse/Open-Source-Requests#120]
### **Integrate Chatwoot inside Vuejs project**

   - **Posted by**: Aviyel Team
   - [Check Status](https://sturdy-locust-74a.notion.site/Chatwoot-27475c4c2ebd48c2a456e6caf525434f)
   - **Standard**: _Unpaid_

**Comment by HeVictor** [comment]
Hi, I would like to give this a crack. Thanks!

**Comment by siddharth2798** [comment]
@HeVictor assigned it to you

**Comment by HeVictor** [comment]
Hi @siddharth2798, I've made a PR for the demo. Sorry it took awhile as I didn't have much time to work on it, but hopefully it passes the bar!
