### ISSUE TITLE
Integrate Chatwoot inside Vanilla HTML project

### ISSUE THREAD

**Issue by siddharth2798** [aviyelverse/Open-Source-Requests#121]
### **Integrate Chatwoot inside Vanilla HTML project**

   - **Posted by**: Aviyel Team
   - [Check Status](https://sturdy-locust-74a.notion.site/Chatwoot-27475c4c2ebd48c2a456e6caf525434f)
   - **Standard**: _Unpaid_

**Comment by Dhravya** [comment]
Hi, I can do this!

**Comment by siddharth2798** [comment]
@Dhravya assigned this to you

**Comment by Dhravya** [comment]
Sent the pull request!
https://github.com/aviyelverse/project-templates-and-demos/pull/3

**Comment by siddharth2798** [comment]
Thanks for this!
