### ISSUE TITLE
Can we have new projects?

### ISSUE THREAD

**Issue by EOEboh** [aviyelverse/Open-Source-Requests#126]
Can we have all projects on the platform listed in this repository?

I can offer to write the markdown.

**Comment by siddharth2798** [comment]
Hey @EOEboh, we unfortunately don't have enough requests on the other projects to populate here. Thanks so much for volunteering.
We are looking for PRs on https://github.com/aviyelverse/aviyel-first-pr. Don't forget to claim your rewards once it's merged ;)
