### ISSUE TITLE
Return version in health check endpoint

### ISSUE THREAD

**Issue by SwamiSankalp** [aviyelverse/Open-Source-Requests#54]
**Is your proposal related to a problem?**
Need a way to check which version is running.

**Describe the solution you'd like**
Return the version in the health check endpoint.

- **Posted by**: _[@deepakprabhakara](https://github.com/deepakprabhakara)_
- <img src="https://img.shields.io/endpoint?url=https%3A%2F%2Faviyel-request-board.herokuapp.com%2Fboxyhq%2F142">
- **Standard**: _Unpaid_
- **[Issue Link](https://github.com/boxyhq/jackson/issues/142?utm_source=github&utm_medium=opensourcegigs&utm_campaign=job+board)**

**Comment by deepakprabhakara** [comment]
@SwamiSankalp This issue can now be closed, thanks.
